apiVersion: v1
kind: Namespace
metadata:
  name: telepresence
---
apiVersion: v1
kind: Service
metadata:
  namespace: telepresence
  name: devapp
spec:
  type: ClusterIP
  selector:
    app: devapp
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: telepresence
  name: backend-1
spec:
  type: ClusterIP
  selector:
    app: backend-1
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: telepresence
  name: backend-2
spec:
  type: ClusterIP
  selector:
    app: backend-2
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: telepresence
  name: curl
spec:
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: buildpack-deps:18.04-curl
        command:
          - sleep
          - '999999'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: telepresence
  name: devapp
spec:
  selector:
    matchLabels:
      app: devapp
  template:
    metadata:
      labels:
        app: devapp
    spec:
      containers:
      - name: devapp
        image: translucens/telepresence-demoapp
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: telepresence
  name: backend-1
spec:
  selector:
    matchLabels:
      app: backend-1
  template:
    metadata:
      labels:
        app: backend-1
    spec:
      containers:
      - name: backend-1
        image: nginx:1.16.0
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: telepresence
  name: backend-2
spec:
  selector:
    matchLabels:
      app: backend-2
  template:
    metadata:
      labels:
        app: backend-2
    spec:
      containers:
      - name: backend-2
        image: httpd:2.4.39
        ports:
        - containerPort: 80
